export const INC_COUNTER = "INC_COUNTER"
export const DEC_COUNTER = "DEC_COUNTER"
export const ADD_NEW_BOOK = "ADD_NEW_BOOK"
export const BOOK_FETCHED = "BOOK_FETCHED"
export const SEARCH_TERM = "SEARCH_TERM"
